eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/  #这个地址既可以提供给其他服务注册，也可以作为自己的注册地址
spring:
  application:
    name: eureka-server     #这个是服务的名称
server:
  port: 1111